### ISSUE TITLE
你确定这样配置能用吗？

### ISSUE THREAD

**Issue by codesourse** [Tangdixi/Baidu-Maps-iOS-SDK.podspec#1]
Undefined symbols for architecture armv7:
  "_MKLaunchOptionsShowsTrafficKey", referenced from:
      ___42-[B2_MapGuidanceViewController showAllMap]_block_invoke in B2_MapGuidanceViewController.o
  "_MKLaunchOptionsDirectionsModeDriving", referenced from:
      ___42-[B2_MapGuidanceViewController showAllMap]_block_invoke in B2_MapGuidanceViewController.o
  "_OBJC_CLASS_$_MKPlacemark", referenced from:
      objc-class-ref in B2_MapGuidanceViewController.o
  "_MKLaunchOptionsDirectionsModeKey", referenced from:
      ___42-[B2_MapGuidanceViewController showAllMap]_block_invoke in B2_MapGuidanceViewController.o
  "_OBJC_CLASS_$_MKMapItem", referenced from:
      objc-class-ref in B2_MapGuidanceViewController.o
ld: symbol(s) not found for architecture armv7

**Comment by Tangdixi** [comment]
#This repo is deprecated

**Comment by Tangdixi** [comment]
Type **pod search Baidu-Maps-iOS-SDK** in your **Terminal** to use the new version

**Comment by codesourse** [comment]
because  of using
MKLaunchOptionsDirectionsModeKey, 
MKLaunchOptionsShowsTrafficKey,
MKLaunchOptionsDirectionsModeDriving

i import <MapKit/MapKit.h> in "AppDelegate.m"
this problem is solved,
but i don't know why.

**Comment by Tangdixi** [comment]
**MKLaunchOptionsShowsTrafficKey** ?  
That's a constant in MapKit. I don't see any connection with Baidu-Maps-iOS-API.  

And what U import into the **AppDelegate**? 

And the current version is **2.6.0**, you prefer to use the new one dude
