### ISSUE TITLE
Not displaying Baidu Map in iOS application

### ISSUE THREAD

**Issue by ZalakSA** [Tangdixi/Baidu-Maps-iOS-SDK.podspec#2]
We are not able to generate api key as well as map is not getting displayed instead we are getting error:-  Engine initialize failure.

Can you please let us know what could be the solution for this?

**Comment by Tangdixi** [comment]
Hey. @Sazalak89.  
Actually this repo is just a unofficial mirror for **Baidu-Maps-iOS-SDK** and deprecated.  
So, you should figure out your issue somewhere else.  Maybe the [official website](http://developer.baidu.com/map/index.php?title=iossdk)
